//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_WS_WF.ServiceHotel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHotel.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément idAgence de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDispo", ReplyAction="*")]
        TP_WS_WF.ServiceHotel.GetDispoResponse GetDispo(TP_WS_WF.ServiceHotel.GetDispoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDispo", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.GetDispoResponse> GetDispoAsync(TP_WS_WF.ServiceHotel.GetDispoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément choix de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImg", ReplyAction="*")]
        TP_WS_WF.ServiceHotel.GetImgResponse GetImg(TP_WS_WF.ServiceHotel.GetImgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImg", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.GetImgResponse> GetImgAsync(TP_WS_WF.ServiceHotel.GetImgRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserver", ReplyAction="*")]
        TP_WS_WF.ServiceHotel.ReserverResponse Reserver(TP_WS_WF.ServiceHotel.ReserverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserver", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.ReserverResponse> ReserverAsync(TP_WS_WF.ServiceHotel.ReserverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDispoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDispo", Namespace="http://tempuri.org/", Order=0)]
        public TP_WS_WF.ServiceHotel.GetDispoRequestBody Body;
        
        public GetDispoRequest() {
        }
        
        public GetDispoRequest(TP_WS_WF.ServiceHotel.GetDispoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDispoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdpAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nbPers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dD;
        
        public GetDispoRequestBody() {
        }
        
        public GetDispoRequestBody(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            this.idAgence = idAgence;
            this.mdpAgence = mdpAgence;
            this.nbPers = nbPers;
            this.dA = dA;
            this.dD = dD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDispoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDispoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_WS_WF.ServiceHotel.GetDispoResponseBody Body;
        
        public GetDispoResponse() {
        }
        
        public GetDispoResponse(TP_WS_WF.ServiceHotel.GetDispoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDispoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TP_WS_WF.ServiceHotel.ArrayOfString GetDispoResult;
        
        public GetDispoResponseBody() {
        }
        
        public GetDispoResponseBody(TP_WS_WF.ServiceHotel.ArrayOfString GetDispoResult) {
            this.GetDispoResult = GetDispoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImg", Namespace="http://tempuri.org/", Order=0)]
        public TP_WS_WF.ServiceHotel.GetImgRequestBody Body;
        
        public GetImgRequest() {
        }
        
        public GetImgRequest(TP_WS_WF.ServiceHotel.GetImgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string choix;
        
        public GetImgRequestBody() {
        }
        
        public GetImgRequestBody(string choix) {
            this.choix = choix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImgResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_WS_WF.ServiceHotel.GetImgResponseBody Body;
        
        public GetImgResponse() {
        }
        
        public GetImgResponse(TP_WS_WF.ServiceHotel.GetImgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetImgResult;
        
        public GetImgResponseBody() {
        }
        
        public GetImgResponseBody(string GetImgResult) {
            this.GetImgResult = GetImgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reserver", Namespace="http://tempuri.org/", Order=0)]
        public TP_WS_WF.ServiceHotel.ReserverRequestBody Body;
        
        public ReserverRequest() {
        }
        
        public ReserverRequest(TP_WS_WF.ServiceHotel.ReserverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numCB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string choixChambre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string idAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mdpAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nbPlace;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime dArr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime dDep;
        
        public ReserverRequestBody() {
        }
        
        public ReserverRequestBody(string nom, string prenom, string numCB, string choixChambre, string idAgence, string mdpAgence, int nbPlace, System.DateTime dArr, System.DateTime dDep) {
            this.nom = nom;
            this.prenom = prenom;
            this.numCB = numCB;
            this.choixChambre = choixChambre;
            this.idAgence = idAgence;
            this.mdpAgence = mdpAgence;
            this.nbPlace = nbPlace;
            this.dArr = dArr;
            this.dDep = dDep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserverResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_WS_WF.ServiceHotel.ReserverResponseBody Body;
        
        public ReserverResponse() {
        }
        
        public ReserverResponse(TP_WS_WF.ServiceHotel.ReserverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserverResult;
        
        public ReserverResponseBody() {
        }
        
        public ReserverResponseBody(string ReserverResult) {
            this.ReserverResult = ReserverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TP_WS_WF.ServiceHotel.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TP_WS_WF.ServiceHotel.WebService1Soap>, TP_WS_WF.ServiceHotel.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_WS_WF.ServiceHotel.GetDispoResponse TP_WS_WF.ServiceHotel.WebService1Soap.GetDispo(TP_WS_WF.ServiceHotel.GetDispoRequest request) {
            return base.Channel.GetDispo(request);
        }
        
        public TP_WS_WF.ServiceHotel.ArrayOfString GetDispo(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            TP_WS_WF.ServiceHotel.GetDispoRequest inValue = new TP_WS_WF.ServiceHotel.GetDispoRequest();
            inValue.Body = new TP_WS_WF.ServiceHotel.GetDispoRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPers = nbPers;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            TP_WS_WF.ServiceHotel.GetDispoResponse retVal = ((TP_WS_WF.ServiceHotel.WebService1Soap)(this)).GetDispo(inValue);
            return retVal.Body.GetDispoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.GetDispoResponse> TP_WS_WF.ServiceHotel.WebService1Soap.GetDispoAsync(TP_WS_WF.ServiceHotel.GetDispoRequest request) {
            return base.Channel.GetDispoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.GetDispoResponse> GetDispoAsync(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            TP_WS_WF.ServiceHotel.GetDispoRequest inValue = new TP_WS_WF.ServiceHotel.GetDispoRequest();
            inValue.Body = new TP_WS_WF.ServiceHotel.GetDispoRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPers = nbPers;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            return ((TP_WS_WF.ServiceHotel.WebService1Soap)(this)).GetDispoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_WS_WF.ServiceHotel.GetImgResponse TP_WS_WF.ServiceHotel.WebService1Soap.GetImg(TP_WS_WF.ServiceHotel.GetImgRequest request) {
            return base.Channel.GetImg(request);
        }
        
        public string GetImg(string choix) {
            TP_WS_WF.ServiceHotel.GetImgRequest inValue = new TP_WS_WF.ServiceHotel.GetImgRequest();
            inValue.Body = new TP_WS_WF.ServiceHotel.GetImgRequestBody();
            inValue.Body.choix = choix;
            TP_WS_WF.ServiceHotel.GetImgResponse retVal = ((TP_WS_WF.ServiceHotel.WebService1Soap)(this)).GetImg(inValue);
            return retVal.Body.GetImgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.GetImgResponse> TP_WS_WF.ServiceHotel.WebService1Soap.GetImgAsync(TP_WS_WF.ServiceHotel.GetImgRequest request) {
            return base.Channel.GetImgAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.GetImgResponse> GetImgAsync(string choix) {
            TP_WS_WF.ServiceHotel.GetImgRequest inValue = new TP_WS_WF.ServiceHotel.GetImgRequest();
            inValue.Body = new TP_WS_WF.ServiceHotel.GetImgRequestBody();
            inValue.Body.choix = choix;
            return ((TP_WS_WF.ServiceHotel.WebService1Soap)(this)).GetImgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_WS_WF.ServiceHotel.ReserverResponse TP_WS_WF.ServiceHotel.WebService1Soap.Reserver(TP_WS_WF.ServiceHotel.ReserverRequest request) {
            return base.Channel.Reserver(request);
        }
        
        public string Reserver(string nom, string prenom, string numCB, string choixChambre, string idAgence, string mdpAgence, int nbPlace, System.DateTime dArr, System.DateTime dDep) {
            TP_WS_WF.ServiceHotel.ReserverRequest inValue = new TP_WS_WF.ServiceHotel.ReserverRequest();
            inValue.Body = new TP_WS_WF.ServiceHotel.ReserverRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.prenom = prenom;
            inValue.Body.numCB = numCB;
            inValue.Body.choixChambre = choixChambre;
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPlace = nbPlace;
            inValue.Body.dArr = dArr;
            inValue.Body.dDep = dDep;
            TP_WS_WF.ServiceHotel.ReserverResponse retVal = ((TP_WS_WF.ServiceHotel.WebService1Soap)(this)).Reserver(inValue);
            return retVal.Body.ReserverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.ReserverResponse> TP_WS_WF.ServiceHotel.WebService1Soap.ReserverAsync(TP_WS_WF.ServiceHotel.ReserverRequest request) {
            return base.Channel.ReserverAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_WS_WF.ServiceHotel.ReserverResponse> ReserverAsync(string nom, string prenom, string numCB, string choixChambre, string idAgence, string mdpAgence, int nbPlace, System.DateTime dArr, System.DateTime dDep) {
            TP_WS_WF.ServiceHotel.ReserverRequest inValue = new TP_WS_WF.ServiceHotel.ReserverRequest();
            inValue.Body = new TP_WS_WF.ServiceHotel.ReserverRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.prenom = prenom;
            inValue.Body.numCB = numCB;
            inValue.Body.choixChambre = choixChambre;
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPlace = nbPlace;
            inValue.Body.dArr = dArr;
            inValue.Body.dDep = dDep;
            return ((TP_WS_WF.ServiceHotel.WebService1Soap)(this)).ReserverAsync(inValue);
        }
    }
}
